# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:55
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170221_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Entrada'),
        ),
    ]
