# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 05:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100, verbose_name='Línea 1')),
                ('line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Línea 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de facturación',
                'verbose_name_plural': 'Direcciones de facturación',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100, verbose_name='Línea 1')),
                ('line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Línea 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de envío',
                'verbose_name_plural': 'Direcciones de envío',
            },
        ),
    ]
