# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 21:48
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170221_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Texto corto'),
        ),
    ]
