# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=25, verbose_name='Autor'),
        ),
    ]
