# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 22:05
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180213_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Autor'),
        ),
    ]
