# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
    ]
