# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='¿Disponible?'),
        ),
    ]
