# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170320_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(max_length=100),
        ),
    ]
