# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170327_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Estatus'),
        ),
    ]
