# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, max_length=255, verbose_name='Método de pago'),
        ),
    ]
