# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reference_pol',
        ),
    ]
